/* This file must be #included in the actual implementation file. */
/* This file has been autogenerated from 'optim.idl'. */
/* Generator component: $Id: c-backend.c,v 1.11 2004/11/19 10:00:34 perez Exp $ */
/* CHANGES TO THIS FILE WILL BE LOST */

#ifndef _GSS_OPTIM_H
#define _GSS_OPTIM_H

#include "signal_interface.h"

#define TMPPATH_TEMPLATE "/tmp/%s.tmp_data"
#define TMPPATH(str, prefix) snprintf(str, sizeof(str), TMPPATH_TEMPLATE, prefix);

#define TMPFILE_TEMPLATE "%s/%s"
#define TMPFILE(str, path, file) snprintf(str, sizeof(str), TMPFILE_TEMPLATE, path, file);

#define STRING(var) char var[MAXPATHLEN]

#ifdef __cplusplus
extern "C" {
#endif

/* The actual functions must use this variable to return their error codes */
extern int gs_result;

typedef char* file;

enum operationCode {Generate_SignalOp, Trace_filterOp, Trace_filter_IPCOp, CutterOp, Cutter_signalOp, MPIStatsOp, EfficiencyOp, AgafaOp, Cutter2Op, Cutter3Op, SenyalDOp, SenyalEOp, Parelles01Op, Trace_filter2Op, Trace_filter3Op, SignalBWOp, SignalMPICallOp, SignalMPIP2POp, SignalMPIP2PgOp, SignalMPIColleOp, SignalRunningOp, SignalDurRunningOp, SignalDurRunninglogOp, FilterRunningOp, SignalIPCOp, SamplerOp, Sampler2Op, FftOp, GeneComOp, FftprevOp, ScOp, Sc_Op, CorrectionOp, GetTimeOp, Sampler_waveletOp, WaveletOp, Compute_shiftOp, Task_shifterOp, ParamedirOp, SubtractionOp, CrosscorrelationOp, StatsOp, Prv2trfOp, GeneratecfgOp, DimemasOp};



Period_t * Analysis(file signal, long long int t0, long long int t1, long int duration, long int r0, long int r1,
int n, int i, int j2, char* option, file trace, int cut, int p, file signal2, file signal3, int* pfound,
long int* period, file signalout, long int* point1, long int* point2, file filename, FILE *out,
FILE *err, int num_chop, char *tmp_dirname, int requested_iters);

/* DEAD_CODE
void BarlettWindowing(struct signal_elem *sig, signalSize siglen);
*/
void applyWindowing(struct signal_elem *sig, signalSize siglen, int window_type);


#ifdef __cplusplus
}
#endif

#endif /* _GSS_OPTIM_H */
