#!/bin/bash

FILE=plot$RANDOM.tmp

echo "set xlabel 'Time'"                       > $FILE
echo "set ylabel 'Value'"                     >> $FILE
echo "plot \"$1\" using 1:3 with steps"       >> $FILE
echo "pause -1 \"Hit return to continue...\"" >> $FILE

gnuplot $FILE

unlink $FILE
